### ISSUE TITLE
xbmcfilm 1.1.5 error - failed to start

### ISSUE THREAD

**Issue by krzaknet** [mrknow/filmkodi#170]
Log ponizej, any ideas dlaczego po aktualizacji do 1.1.5 wtyczka nie startuje

OpenELECT 6.0.3
Kodi 15.2

21:44:30 123.161827 T:1586721856  NOTICE: -->Python Interpreter Initialized<--
21:44:36 128.945145 T:1586721856   ERROR: EXCEPTION: Unknown addon id 'plugin.video.mrknow'.
21:44:36 129.001297 T:1586721856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'plugin.video.mrknow'.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.xbmcfilm/default.py", line 21, in <module>
                                                import mrknow_pLog, settings, mrknow_Parser, xbmcfilmapi, mrknow_urlparser, mrknow_Player, mrknow_pCommon
                                              File "/storage/.kodi/addons/plugin.video.xbmcfilm/resources/lib/mrknow_urlparser.py", line 19, in <module>
                                                ptv = xbmcaddon.Addon(scriptID)
                                            RuntimeError: Unknown addon id 'plugin.video.mrknow'.
                                            -->End of Python script error report<--
21:44:37 129.700134 T:1967370240   ERROR: GetDirectory - Error getting plugin://plugin.video.xbmcfilm/
21:44:37 129.713226 T:1967370240   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.xbmcfilm/) failed
21:44:37 129.777115 T:1586721856  NOTICE: Thread BackgroundLoader start, auto delete: false
21:44:41 133.407791 T:1586721856  NOTICE: Thread LanguageInvoker start, auto delete: false

**Comment by krzaknet** [comment]
RuntimeError: Unknown addon id 'plugin.video.mrknow'.

Nie ma tematu.
