### ISSUE TITLE
Error in Specto when changing movie and series directory to Nas location

### ISSUE THREAD

**Issue by Maverick3037** [mrknow/filmkodi#182]
Mr Know,

Using the latest version 2016.03.50.1 but still get an error message as soon as I want to change the library directory to a folder on my NAS.
Tried to link as ftp or NFS, both without any luck.
As soon as I change it back to the default folders it resolves the error message.
Copied in the error message below.

22:40:51 T:1456   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/?action=toolNavigator
22:40:51 T:1456   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/?action=toolNavigator) failed
22:40:51 T:4612   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 123] De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist: 'ftp:'
                                            Traceback (most recent call last):
                                              File "C:\Users\Maverick\AppData\Roaming\Kodi\addons\plugin.video.specto\default.py", line 126, in <module>
                                                navigator.navigator().root()
                                              File "C:\Users\Maverick\AppData\Roaming\Kodi\addons\plugin.video.specto\resources\lib\indexers\navigator.py", line 56, in __init__
                                                os.makedirs(tv_library)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 123] De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist: 'ftp:'
                                            -->End of Python script error report<--

Hope you can help.
Regards
Maverick

**Comment by xscode** [comment]
I having the same problem, it was working until the most recent update.

`File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.specto/resources/lib/indexers/navigator.py", line 56, in __init__
                                                os.makedirs(tv_library)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/os.py", line 150, in makedirs
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/os.py", line 150, in makedirs
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/os.py", line 150, in makedirs
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/os.py", line 157, in makedirs
                                            OSError: [Errno 30] Read-only file system: 'nfs:'
                                            -->End of Python script error report<--
11:32:42 T:1390168368   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.specto/
11:32:42 T:1390168368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/) failed
`

**Comment by amxcoder** [comment]
I am also seeing this issue.  Set the library locations to a SMB share, and Specto now crashes when opening.  Just installed Specto and was attempting to setup with shared network library, and as soon as I did, it crashes the addon.  It keeps crashing each time I try to open it.

Running on: Amazon FireTV 4K, SPMC Isengard, plugin version 2016.04.11.1

**Comment by mrknow** [comment]
Try new version 2016.05.8.4

**Comment by mrbill13** [comment]
I am running specto 2016.05.10.5 kodi 16.1 on both win 10 and android 5.1. As soon as I change library folder location to a network share specto crashes and wont launch again until library is moved to a local drive instead of network location.
