### ISSUE TITLE
dodatek cda.pl > wyszukaj nie radzi sobie ze spacjami

### ISSUE THREAD

**Issue by widgetpl** [mrknow/filmkodi#23]
niestety nie mogłem znaleźć metody quote_plus() w module urllib ani urllib3 żeby przetestować
```python
    def getSearchURL(self, key):
        url = 'http://www.cda.pl/video/show/' + urllib.quote_plus(key) +'/p1?s=best'
        #http://www.cda.pl/video/show/xxx/p2?s=best
        return url
```
logi:
```
19:51:13 T:140048741689088  NOTICE: [xbmcfilm.com  1] Starting cdapl.pl
19:51:13 T:140048741689088  NOTICE: ('Dane', 'None', 'main-menu', 'Szukaj', 'None')
19:51:19 T:140048741689088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: 
                                            Traceback (most recent call last):
                                              File "/home/michal/.kodi/addons/plugin.video.mrknow/default.py", line 867, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/home/michal/.kodi/addons/plugin.video.mrknow/default.py", line 336, in showListOptions
                                                tv.handleService()
                                              File "/home/michal/.kodi/addons/plugin.video.mrknow/host/cdapl.py", line 272, in handleService
                                                self.listsItems(self.getSearchURL(key))
                                              File "/home/michal/.kodi/addons/plugin.video.mrknow/host/cdapl.py", line 87, in listsItems
                                                link = self.cm.getURLRequestData(query_data)
                                              File "/home/michal/.kodi/addons/plugin.video.mrknow/resources/lib/libCommon.py", line 156, in getURLRequestData
                                                response = opener.open(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 475, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: 
                                            -->End of Python script error report<--
19:51:19 T:140050821224384   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?category=Szukaj&icon=None&name=main-menu&service=cdapl&strona&title=None&url=None
19:51:19 T:140050821224384   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?category=Szukaj&icon=None&name=main-menu&service=cdapl&strona&title=None&url=None) failed
```

cda.pl zamienia spacje na "_"
Teraz zauważyłem że to jest 2.7 a nie 3:

```python
>>> import urllib2
>>> urllib2.quote("cos innego")
'cos%20innego'
```

**Comment by widgetpl** [comment]
Problem dotyczył konkretnego wyszukiwania :/
