### ISSUE TITLE
Library integration still not working

### ISSUE THREAD

**Issue by Scotster** [mrknow/filmkodi#343]
Yet another thread closed without MrKnow reading it. Seriously, why even have an "issues" area if you're going to completely ignore what people are writing.

So here we go AGAIN. Note the bit in bold with the stars around it. There's a hint in there about what the issue isn't. Not the most tuned in of devs are you?

Everytime I see a thread on this it gets closed out as fixed. At no point has this issue been resolved. I'm not sure how well the problem is being looked into but there seems to be a clear misunderstanding with what the issue is. If the issue is not cared about then please let me know, my workaround is fine.... but please stop saying it's fixed when it isn't.

I apologise if this is really dumbed down but every time I cut to the chase with the issue it gets completely overlooked and "Fixed" gets stamped on the thread so I'm guessing I'm either not explaining well enough or there are wrong assumptions about what the issue is being made.

Specto - Tools - Specto:Library - Library:Settings - Movies and/or TV

*******PLEASE NOTE I'M NOT TALKING ABOUT "DOWNLOADS"*********

There is no way to select SMB as the option for the location of strm files. Local is the only option. If the "Settings.xml" file is manually changed on the following lines.....

```
<setting id="movie_library" value="smb://SMBShare/Movies/" />
<setting id="tv_library" value="smb://SMBShare/TV Shows//" />
```

It won't work, Specto won't open and the following log is generated......

```
13:29:02 T:6532  NOTICE: [SPECTO]: ->----------                PARAMS: {}
13:29:02 T:6532   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\default.py", line 139, in <module>
                                                navigator.navigator().root()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\resources\lib\indexers\navigator.py", line 51, in __init__
                                                if not os.path.exists(movie_library): os.makedirs(movie_library)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            -->End of Python script error report<--
13:29:02 T:6820   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/
13:29:02 T:6820   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/) failed
13:29:02 T:6532  NOTICE: [SPECTO]: ->----------                PARAMS: {}
13:29:02 T:6532   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\default.py", line 139, in <module>
                                                navigator.navigator().root()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\resources\lib\indexers\navigator.py", line 51, in __init__
                                                if not os.path.exists(movie_library): os.makedirs(movie_library)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            -->End of Python script error report<--
13:29:02 T:6820   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/
13:29:02 T:6820   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/) failed
```

The ONLY way I have got this to work is to remove the following code in the"\addons\plugin.video.specto\resources\lib\indexers\navigator.py" file

```
53	        if not os.path.exists(movie_library):	
54	            os.makedirs(movie_library)			
55	        if not os.path.exists(tv_library):			
56	            os.makedirs(tv_library)			
57	        if not os.path.exists(tv_downloads):			
58	            os.makedirs(tv_downloads)			
59	        if not os.path.exists(movie_downloads):			
60	            os.makedirs(movie_downloads)
```

The above solves my issue.

Please if you read this MrKnow, take some time to understand what I'm talking about here. If you do not wish to address this issue please simply let me know and I'll stop harping on about it. Please don't mark it as "solved" when it's not though.

**Comment by xxcriticxx** [comment]
@Scotster he will get to it he is one man show. i know this issue still open because i tested it with you. sorry for delay

**Comment by Scotster** [comment]
He closed the other thread though, as if the issue was solved. Pointed me to the FAQ regarding downloads (which is not the issue).

Far too dismissive and makes the assumption that he knows what the issue is without even reading the thread.

**Comment by mrknow** [comment]
@Scotster Hi , sorry I do not understand this error. For me it did not exist . Try this solution , and write that helped

>         try:
            if not os.path.exists(movie_library): os.makedirs(movie_library)
        except:
            pass
        try:
            if not os.path.exists(tv_library): os.makedirs(tv_library)
        except:
            pass

**Comment by Scotster** [comment]
That doesn't work either. I'll make a small video showing the issue.

**Comment by Scotster** [comment]
Here is a video of the issue.

Firstly the addon opens fine with the default settinsg.
I then change the library share to my SMB server folder which breaks the system
I then edit the navigator.py to hash out 2 lines of code which fixes the issue
I then edit the navigator.py back to standard to show that it's these 2 lines causing the issue.
I then edit the navigator.py to implement your new code to show it has no effect.

https://www.youtube.com/watch?v=ppcSuXK2vuA
