### ISSUE TITLE
Problem z wtyczką błąd przy wyborze playera

### ISSUE THREAD

**Issue by armkon** [mrknow/filmkodi#43]
Po aktualizacji kodi  tym razem na raspberry pi2 lista programów ładuje się, jednek przy odpaleniu dowolnego źródła ze streamem dostaję komunikat o błędzie. Poniżej to co znalazłem w logu:

Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'PLAYER_CORE_AUTO'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mrknow/default.py", line 920, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.mrknow/default.py", line 261, in showListOptions
                                                self.playVideo(videos[0], True)
                                              File "/storage/.kodi/addons/plugin.video.mrknow/default.py", line 514, in playVideo
                                                xbmc.Player(self.getPlayerType()).play(url, listitem)
                                              File "/storage/.kodi/addons/plugin.video.mrknow/default.py", line 520, in getPlayerType
                                                return xbmc.PLAYER_CORE_AUTO
                                            AttributeError: 'module' object has no attribute 'PLAYER_CORE_AUTO'

Jakieś propozycje?

**Comment by mrknow** [comment]
Wgraj ręcznie te wtyczki  poprzez opcje zainstaluj z pliku zip
1. najpierw - script.module.xbmcfilm.zip
2. następnie - plugin.video.mrknow.zip
3. jako opcje jeszcze raz repozytorium repository.filmkodi.com.zip

[script.module.xbmcfilm.zip](https://github.com/mrknow/filmkodi/files/107510/script.module.xbmcfilm.zip)
[plugin.video.mrknow.zip](https://github.com/mrknow/filmkodi/files/107509/plugin.video.mrknow.zip)
[repository.filmkodi.com.zip](https://github.com/mrknow/filmkodi/files/107511/repository.filmkodi.com.zip)

**Comment by badsector3** [comment]
Ten sam problem. Zainstalowalem te 3 wtyczki - nadal to samo.

**Comment by mrknow** [comment]
Stare zgłoszenie. Proszę otworzyć ponownie jeżeli błąd nadal występuje
