### ISSUE TITLE
Whole OSMC crash if you hit back while some service is loading

### ISSUE THREAD

**Issue by mkukulski** [mrknow/filmkodi#487]
Go to Addons -> Filmy Online - mrknow.pl
Select Bajki -> Bajkionline.com  -> Ostatnio dodane
While it is loading press Return.
Kodi crash 
Bellow logs from crash
Addon version 2016.09.04.01
System RaspberryPi OSMC 2016.08-1 kernel 4.4.16-4-osmc

```
11:38:09 416274.468750 T:2470781936  NOTICE: ES: Stopping event server with confirmation
11:38:10 416275.281250 T:2746217456  NOTICE: ES: UDP Event server stopped
11:38:10 416275.312500 T:2746217456  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
11:38:10 416275.312500 T:2746217456  NOTICE: UDP: Listening on port 9777
11:39:49 416373.968750 T:2746217456  NOTICE: ES: Client  from 192.168.1.222 timed out
11:55:34 417318.625000 T:2574250992  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.09.13.1
11:55:35 417319.781250 T:2574250992  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
11:55:35 417319.781250 T:2574250992  NOTICE: [plugin.video.mrknow]
11:55:35 417319.781250 T:2574250992  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
11:55:35 417319.781250 T:2574250992  NOTICE: [plugin.video.mrknow] Handle: 6
11:55:35 417319.812500 T:2574250992  NOTICE: [plugin.video.mrknow] Parameter:
11:55:35 417319.812500 T:2574250992  NOTICE: [plugin.video.mrknow] LEN: 0
11:55:35 417319.812500 T:2574250992  NOTICE: [plugin.video.mrknow] mode: None
11:55:35 417319.812500 T:2574250992  NOTICE: [plugin.video.mrknow] Wyświetlam kategorie
11:56:14 417359.437500 T:2574250992  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.09.13.1
11:56:16 417360.687500 T:2574250992  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
11:56:16 417360.687500 T:2574250992  NOTICE: [plugin.video.mrknow] ?mode=7
11:56:16 417360.687500 T:2574250992  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
11:56:16 417360.687500 T:2574250992  NOTICE: [plugin.video.mrknow] Handle: 7
11:56:16 417360.687500 T:2574250992  NOTICE: [plugin.video.mrknow] Parameter: ?mode=7
11:56:16 417360.687500 T:2574250992  NOTICE: [plugin.video.mrknow] LEN: 7
11:56:16 417360.687500 T:2574250992  NOTICE: [plugin.video.mrknow] mode: 7
11:56:40 417385.500000 T:2574250992  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.09.13.1
11:56:42 417386.718750 T:2574250992  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
11:56:42 417386.718750 T:2574250992  NOTICE: [plugin.video.mrknow] ?mode=10020
11:56:42 417386.718750 T:2574250992  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
11:56:42 417386.718750 T:2574250992  NOTICE: [plugin.video.mrknow] Handle: 8
11:56:42 417386.718750 T:2574250992  NOTICE: [plugin.video.mrknow] Parameter: ?mode=10020
11:56:42 417386.718750 T:2574250992  NOTICE: [plugin.video.mrknow] LEN: 11
11:56:42 417386.718750 T:2574250992  NOTICE: [plugin.video.mrknow] mode: 10020
11:56:42 417386.750000 T:2574250992  NOTICE: [plugin.video.mrknow] Starting bajkionline.pl
11:56:42 417386.750000 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:main-menu, category:Ostatnio dodane, title:None, iconimage:None, url:None, desc:None, rating:None
11:56:42 417386.750000 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:main-menu, category:Spis, title:None, iconimage:None, url:None, desc:None, rating:None
11:57:03 417408.531250 T:2574250992  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.09.13.1
11:57:05 417409.750000 T:2574250992  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
11:57:05 417409.781250 T:2574250992  NOTICE: [plugin.video.mrknow] ?category=Spis&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None
11:57:05 417409.781250 T:2574250992  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
11:57:05 417409.781250 T:2574250992  NOTICE: [plugin.video.mrknow] Handle: 9
11:57:05 417409.781250 T:2574250992  NOTICE: [plugin.video.mrknow] Parameter: ?category=Spis&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None
11:57:05 417409.781250 T:2574250992  NOTICE: [plugin.video.mrknow] LEN: 86
11:57:05 417409.781250 T:2574250992  NOTICE: [plugin.video.mrknow] mode: None
11:57:05 417409.781250 T:2574250992  NOTICE: [plugin.video.mrknow] Starting bajkionline.pl
12:01:59 417704.093750 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:categories-menu, category:6 w pracy, title:None, iconimage:None, url:http://bajkionline.com/category/6-w-pracy, desc:aaaa, rating:None
12:01:59 417704.093750 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:categories-menu, category:ABC Literkowe Chochliki, title:None, iconimage:None, url:http://bajkionline.com/category/abc-literkowe-chochliki, desc:aaaa, rating:None
12:01:59 417704.125000 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:categories-menu, category:Adibu, title:None, iconimage:None, url:http://bajkionline.com/category/adibu, desc:aaaa, rating:None
12:01:59 417704.156250 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:categories-menu, category:Agent Specjalny Oso, title:None, iconimage:None, url:http://bajkionline.com/category/agent-specjalny-oso, desc:aaaa, rating:None
12:01:59 417704.156250 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:categories-menu, category:Akwalans, title:None, iconimage:None, url:http://bajkionline.com/category/akwalans, desc:aaaa, rating:None
12:01:59 417704.187500 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:categories-menu, category:Aladyn, title:None, iconimage:None, url:http://bajkionline.com/category/aladyn, desc:aaaa, rating:None
12:01:59 417704.187500 T:2574250992  NOTICE: [plugin.video.mrknow] service:bajkionline, name:categories-menu, category:Andy Pandy, title:None, iconimage:None, url:http://bajkionline.com/category/andy-pandy, desc:aaaa, rating:None
12:01:59 417704.218750 T:2574250992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc4 in position 61: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 931, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 361, in showListOptions
                                                tv.handleService()
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/bajkionline.py", line 149, in handleService
                                                self.listsCategoriesMenu(mainUrl)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/bajkionline.py", line 50, in listsCategoriesMenu
                                                self.add('bajkionline', 'categories-menu', self.cm.html_special_chars(mylink.a.text.encode('utf-8')),'None', 'None', mylink.a['href'], 'aaaa', 'None', True, False)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/bajkionline.py", line 90, in add
                                                self.log.info("service:%s, name:%s, category:%s, title:%s, iconimage:%s, url:%s, desc:%s, rating:%s" %(service, name, category, title, iconimage, url, desc, rating))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 61: ordinal not in range(128)
                                            -->End of Python script error report<--
12:02:00 417705.437500 T:3023393712   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?category=Spis&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None
12:02:00 417705.437500 T:3023393712   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?category=Spis&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None) failed
12:02:39 417743.593750 T:2574250992  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.09.13.1
12:02:40 417744.843750 T:2574250992  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
12:02:40 417744.843750 T:2574250992  NOTICE: [plugin.video.mrknow] ?category=Ostatnio dodane&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None
12:02:40 417744.843750 T:2574250992  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
12:02:40 417744.843750 T:2574250992  NOTICE: [plugin.video.mrknow] Handle: 10
12:02:40 417744.843750 T:2574250992  NOTICE: [plugin.video.mrknow] Parameter: ?category=Ostatnio%20dodane&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None
12:02:40 417744.843750 T:2574250992  NOTICE: [plugin.video.mrknow] LEN: 97
12:02:40 417744.843750 T:2574250992  NOTICE: [plugin.video.mrknow] mode: None
12:02:40 417744.875000 T:2574250992  NOTICE: [plugin.video.mrknow] Starting bajkionline.pl
12:02:52 417757.187500 T:3023393712   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?category=Ostatnio%20dodane&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None
12:02:52 417757.187500 T:3023393712   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?category=Ostatnio%20dodane&icon=None&name=main-menu&service=bajkionline&strona&title=None&url=None) failed
12:02:58 417763.218750 T:2729440240   ERROR: CPythonInvoker(19, /home/osmc/.kodi/addons/plugin.video.mrknow/default.py): script didn't stop in 5 seconds - let's kill it

```

**Comment by mrknow** [comment]
old issue

**Comment by mkukulski** [comment]
Co znaczy old issue? Wiem że takie coś jest i nie będę naprawiał czy już zostało naprawione w takim bądz razie w którym buildzie?
