### ISSUE TITLE
cda.pl nie działa alfabetyczna lista filmów

### ISSUE THREAD

**Issue by rysson** [mrknow/filmkodi#540]
Przy wyborze alfabetycznego spisu filmów wyskakuje wyjątek.

```
11:27:34 T:139666565101312  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.10.21.1
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] ?category=Filmy alfabetycznie&icon=None&name=main-menu&service=cdapl&strona&title=None&url=None
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] Handle: 16
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] Parameter: ?category=Filmy%20alfabetycznie&icon=None&name=main-menu&service=cdapl&strona&title=None&url=None
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] LEN: 95
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] mode: None
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] Starting cdapl.pl
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] [cda.pl] url:None
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] Jest Alfabetycznie:
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] CDA.pl - Logowanie xxxxxx@gmail.com
11:27:34 T:139666565101312  NOTICE: [plugin.video.mrknow] CDA.PL - PREMIUM NIE
11:27:34 T:139666565101312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: s=alf
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.video.mrknow/default.py", line 931, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/home/xbmc/.kodi/addons/plugin.video.mrknow/default.py", line 398, in showListOptions
                                                tv.handleService()
                                              File "/home/xbmc/.kodi/addons/plugin.video.mrknow/host/cdapl.py", line 311, in handleService
                                                self.listsItems('s=alf')
                                              File "/home/xbmc/.kodi/addons/plugin.video.mrknow/host/cdapl.py", line 139, in listsItems
                                                link = self.cm.getURLRequestData(query_data)
                                              File "/home/xbmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_pCommon.py", line 230, in getURLRequestData
                                                response = urlOpen(req, customOpeners)
                                              File "/home/xbmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_pCommon.py", line 177, in urlOpen
                                                response = opener.open(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 421, in open
                                                protocol = req.get_type()
                                              File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
                                                raise ValueError, "unknown url type: %s" % self.__original
                                            ValueError: unknown url type: s=alf
                                            -->End of Python script error report<--
11:27:34 T:139667843480384   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?category=Filmy%20alfabetycznie&icon=None&name=main-menu&service=cdapl&strona&title=None&url=None
11:27:34 T:139667843480384   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?category=Filmy%20alfabetycznie&icon=None&name=main-menu&service=cdapl&strona&title=None&url=None) failed
```

**Comment by rysson** [comment]
Błędnie składany URL. Znaczy w ogóle nie go nie było. W pozostałych opcjach był błędny i ignorowany, więc opcje zachowywały się jak „najtrafniejsze”.

Patch na kolanie:
```diff
diff --git a/plugin.video.mrknow/host/cdapl.py b/plugin.video.mrknow/host/cdapl.py
index fb7a1a5..25529d0 100644
--- a/plugin.video.mrknow/host/cdapl.py
+++ b/plugin.video.mrknow/host/cdapl.py
@@ -299,20 +299,20 @@ class cdapl(object):
             
         elif name == 'main-menu' and category == 'Filmy najtrafniejsze':
             log.info('Jest Najtrafniejsze: ')
-            self.listsItems(movies +'s=best')
+            self.listsItems(movies +'?s=best')
         elif name == 'main-menu' and category == 'Filmy najwyżej ocenione':
             log.info('Jest Najwyżej ocenione: ')
-            self.listsItems(movies +'s=rate')
+            self.listsItems(movies +'?s=rate')
         elif name == 'main-menu' and category == 'Filmy popularne':
             log.info('Jest Popularne: ')
-            self.listsItems(movies +'s=popular')
+            self.listsItems(movies +'?s=popular')
         elif name == 'main-menu' and category == 'Filmy najnowsze':
             log.info('Jest Najnowsze: ')
             #self.listsItems(movies +'s=date')
             self.listsItems(movies + '?duration=all&section=&quality=all&section=&s=date&section=')
         elif name == 'main-menu' and category == 'Filmy alfabetycznie':
             log.info('Jest Alfabetycznie: ')
-            self.listsItems('s=alf')
+            self.listsItems(movies + '?s=alf')
         elif name == 'main-menu' and category == "Szukaj":
             key = self.searchInputText()
             if key != None:
```
