### ISSUE TITLE
Specto wont find any streams..."check log for more information"

### ISSUE THREAD

**Issue by Hulumanu** [mrknow/filmkodi#567]
When I click on a tv episode to search for streams, an error occurs... I've tried reinstalling, cleaning the library (though it happens when just in the addon itself), rebooting, clearing data, memory, nothing seems to make it work again..... I can get streams to work in Exodus, but not Specto.

Http://paste.filmkodi.com/pbwmvebgk

Thanks for your time, this is one of the best addons in kodi... library integration is the best!

**Comment by mrknow** [comment]
Thx - i see problem with script.mrknow.urlresolver

Maybe the problem was temporary (while script.mrknow.urlresolver update it self). If not reinstall script.mrknow.urlresolver  from here http://kodi.filmkodi.com/script.mrknow.urlresolver/script.mrknow.urlresolver-2016.11.1.2.zip



>  NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <type 'exceptions.ImportError'
>Error Contents: No module named plugins Traceback (most recent call last):
>                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.specto/default.py", line 369, in <module>
 >                                               from resources.lib.sources import sources
 >                                             File "/storage/sdcard1/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.specto/resources/lib/sources/__init__.py", line 30, in <module>
>                                                import urlresolver9 as urlresolver
>                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py", line 37, in <module>
                                                from plugins import *
                                            ImportError: No module named plugins
                                            -->End of Python script error report<--

**Comment by Hulumanu** [comment]
That worked!  Thank you!!!
