### ISSUE TITLE
mrknow - seriale 

### ISSUE THREAD

**Issue by kamui86** [mrknow/filmkodi#622]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: windows 10

---
## Addon / Wtyczka
- [ x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Wystąpił błąd podczas ładowania jakiegokolwiek serialu kodi zwraca błąd wtyki mrknow...
log:

18:19:45 T:6868  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
18:19:46 T:6868  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
18:19:46 T:6868  NOTICE: [plugin.video.mrknow] ?mode=3
18:19:46 T:6868  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
18:19:46 T:6868  NOTICE: [plugin.video.mrknow] Handle: 52
18:19:46 T:6868  NOTICE: [plugin.video.mrknow] Parameter: ?mode=3
18:19:46 T:6868  NOTICE: [plugin.video.mrknow] LEN: 7
18:19:46 T:6868  NOTICE: [plugin.video.mrknow] mode: 3
18:19:47 T:9964  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] ?mode=8300
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] Handle: 53
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] Parameter: ?mode=8300
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] LEN: 10
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] mode: 8300
18:19:47 T:9964  NOTICE: [plugin.video.mrknow] Starting alltubeseriale.pl
18:19:50 T:9952  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] ?category=Alfabetycznie&icon=None&name=main-menu&service=alltubeseriale&strona&title=None&url=None
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] Handle: 54
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] Parameter: ?category=Alfabetycznie&icon=None&name=main-menu&service=alltubeseriale&strona&title=None&url=None
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] LEN: 98
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] mode: None
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] Starting alltubeseriale.pl
18:19:50 T:9952  NOTICE: [plugin.video.mrknow] Jest Alfabetycznie:
18:20:00 T:9952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.timeout'>
                                            Error Contents: timed out
                                            Traceback (most recent call last):
                                              File "C:\Users\kamui\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 928, in <module>
                                                init.showListOptions(sys.argv)
                                              File "C:\Users\kamui\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 373, in showListOptions
                                                tv.handleService()
                                              File "C:\Users\kamui\AppData\Roaming\Kodi\addons\plugin.video.mrknow\host\alltubeseriale.py", line 282, in handleService
                                                self.listsItemsA(catUrl)
                                              File "C:\Users\kamui\AppData\Roaming\Kodi\addons\plugin.video.mrknow\host\alltubeseriale.py", line 143, in listsItemsA
                                                link = self.cm.getURLRequestData(query_data)
                                              File "C:\Users\kamui\AppData\Roaming\Kodi\addons\plugin.video.mrknow\lib\mrknow_pCommon.py", line 232, in getURLRequestData
                                                response = urlOpen(req, customOpeners)
                                              File "C:\Users\kamui\AppData\Roaming\Kodi\addons\plugin.video.mrknow\lib\mrknow_pCommon.py", line 179, in urlOpen
                                                response = urllib2.urlopen(req)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 404, in open
                                                response = self._open(req, data)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 422, in _open
                                                '_open', req)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1214, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1187, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 1067, in getresponse
                                                response.begin()
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 409, in begin
                                                version, status, reason = self._read_status()
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 365, in _read_status
                                                line = self.fp.readline(_MAXLINE + 1)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\socket.py", line 476, in readline
                                                data = self._sock.recv(self._rbufsize)
                                            timeout: timed out
                                            -->End of Python script error report<--
18:20:00 T:5780   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mrknow/?category=Alfabetycznie&icon=None&name=main-menu&service=alltubeseriale&strona&title=None&url=None
18:20:00 T:5780   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?category=Alfabetycznie&icon=None&name=main-menu&service=alltubeseriale&strona&title=None&url=None) failed
18:20:00 T:9972  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] ?mode=8300
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] Handle: 55
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] Parameter: ?mode=8300
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] LEN: 10
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] mode: 8300
18:20:00 T:9972  NOTICE: [plugin.video.mrknow] Starting alltubeseriale.pl

**Comment by rysson** [comment]
```
data = self._sock.recv(self._rbufsize)
timeout: timed out
```

Wygląda na to, że nie odpowiada na dostęp. Swoją drogą to wtyczka nie powinna rzucać wyjątkiem.
A jak to wygląda gdzie indziej, np. przez stronę? Działa coś?

P.S. Dzięki za wypełnienie formularza – jesteś pierwszym, któremu się to udało :-)

**Comment by rysson** [comment]
@kamui86, jeszcze jedno, to ma być strumień, czy już na liście się wywala?

**Comment by rysson** [comment]
Już widzę, lista alfabetyczna:
```python
        elif name == 'main-menu' and category == 'Alfabetycznie':
            log.info('Jest Alfabetycznie: ')
            self.listsItemsA(catUrl)
```

**Comment by kamui86** [comment]
Na liście wywalało, już działa normalnie.

**Comment by rysson** [comment]
@kamui86, dzieki za info. Też sprawdzałem i działa. Coś się zacięło po ich stronie. Po naszej możemy komunikat dodać. Ale to pewnie później bo i tak planuję sprzątanie w kodzie. Ale to powoli, żeby czegoś nie popsuć.
