### ISSUE TITLE
mrknow.pl - seriale nie działają

### ISSUE THREAD

**Issue by happy2w8** [mrknow/filmkodi#643]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 32-bit version 3.16.36 for Raspberry Pi
- OS version: _____

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [x] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Nagle przestało dziatrzłać wyszukiwanie seriali. Bo wyborze Filmy online - Mrknow.pl -> Seriale -> Zobaczto.tv Seriale -> Alfabetycznie -> (litera) dostaje błąd wtyczki. Jeszcze dwa dni temu wszystko działało bez problemu. Poniżej log:

08:28:58 32153.744141 T:1680860144  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
08:28:58 32153.746094 T:1680860144  NOTICE: [plugin.video.mrknow] ?mode=3
08:28:58 32153.746094 T:1680860144  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
08:28:58 32153.746094 T:1680860144  NOTICE: [plugin.video.mrknow] Handle: 4
08:28:58 32153.746094 T:1680860144  NOTICE: [plugin.video.mrknow] Parameter: ?mode=3
08:28:58 32153.746094 T:1680860144  NOTICE: [plugin.video.mrknow] LEN: 7
08:28:58 32153.746094 T:1680860144  NOTICE: [plugin.video.mrknow] mode: 3
08:29:02 32157.611328 T:1680860144  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
08:29:02 32157.750000 T:1680860144  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
08:29:02 32157.751953 T:1680860144  NOTICE: [plugin.video.mrknow] ?mode=8100
08:29:02 32157.751953 T:1680860144  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
08:29:02 32157.751953 T:1680860144  NOTICE: [plugin.video.mrknow] Handle: 5
08:29:02 32157.751953 T:1680860144  NOTICE: [plugin.video.mrknow] Parameter: ?mode=8100
08:29:02 32157.751953 T:1680860144  NOTICE: [plugin.video.mrknow] LEN: 10
08:29:02 32157.751953 T:1680860144  NOTICE: [plugin.video.mrknow] mode: 8100
08:29:02 32157.751953 T:1680860144  NOTICE: [plugin.video.mrknow] Starting zobacztoseriale.pl
08:29:05 32161.355469 T:1680860144  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
08:29:05 32161.501953 T:1680860144  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
08:29:05 32161.501953 T:1680860144  NOTICE: [plugin.video.mrknow] ?category=Alfabetycznie&icon=None&name=main-menu&service=zobacztoseriale&strona&title=None&url=None
08:29:05 32161.501953 T:1680860144  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
08:29:05 32161.501953 T:1680860144  NOTICE: [plugin.video.mrknow] Handle: 6
08:29:05 32161.501953 T:1680860144  NOTICE: [plugin.video.mrknow] Parameter: ?category=Alfabetycznie&icon=None&name=main-menu&service=zobacztoseriale&strona&title=None&url=None
08:29:05 32161.501953 T:1680860144  NOTICE: [plugin.video.mrknow] LEN: 99
08:29:05 32161.503906 T:1680860144  NOTICE: [plugin.video.mrknow] mode: None
08:29:05 32161.503906 T:1680860144  NOTICE: [plugin.video.mrknow] Starting zobacztoseriale.pl
08:29:05 32161.503906 T:1680860144  NOTICE: [plugin.video.mrknow] Jest Alfabetycznie:
08:29:12 32168.562500 T:1680860144  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
08:29:13 32168.707031 T:1680860144  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
08:29:13 32168.708984 T:1680860144  NOTICE: [plugin.video.mrknow] ?category=None&icon=None&name=page-menu&service=zobacztoseriale&strona&title=P&url=http://zobaczto.tv/
08:29:13 32168.708984 T:1680860144  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
08:29:13 32168.708984 T:1680860144  NOTICE: [plugin.video.mrknow] Handle: 7
08:29:13 32168.708984 T:1680860144  NOTICE: [plugin.video.mrknow] Parameter: ?category=None&icon=None&name=page-menu&service=zobacztoseriale&strona&title=P&url=http%3a%2f%2fzobaczto.tv%2f
08:29:13 32168.708984 T:1680860144  NOTICE: [plugin.video.mrknow] LEN: 102
08:29:13 32168.708984 T:1680860144  NOTICE: [plugin.video.mrknow] mode: None
08:29:13 32168.708984 T:1680860144  NOTICE: [plugin.video.mrknow] Starting zobacztoseriale.pl
08:29:13 32168.710938 T:1680860144  NOTICE: [plugin.video.mrknow] Jest Alfabetycznie Litera: P
08:29:13 32168.751953 T:1680860144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -5] No address associated with hostname>
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 928, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 367, in showListOptions
                                                tv.handleService()
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/zobacztoseriale.py", line 284, in handleService
                                                self.listsItemsS(catUrl,title)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/zobacztoseriale.py", line 141, in listsItemsS
                                                link = self.cm.getURLRequestData(query_data)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_pCommon.py", line 232, in getURLRequestData
                                                response = urlOpen(req, customOpeners)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_pCommon.py", line 179, in urlOpen
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 431, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 449, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno -5] No address associated with hostname>
                                            -->End of Python script error report<--
08:29:13 32168.990234 T:1957016496   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?category=None&icon=None&name=page-menu&service=zobacztoseriale&strona&title=P&url=http%3a%2f%2fzobaczto.tv%2f
08:29:13 32168.992188 T:1957016496   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?category=None&icon=None&name=page-menu&service=zobacztoseriale&strona&title=P&url=http%3a%2f%2fzobaczto.tv%2f) failed
08:29:21 32177.361328 T:1503495152 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.mrknow/?mode=20
08:29:21 32177.363281 T:1503495152   ERROR: InputStream: Error opening, plugin://plugin.video.mrknow/?mode=20
09:20:38 35253.644531 T:1722807280   ERROR: GetDirectory - Error getting /home/osmc/.kodi/userdata/addon_data/plugin.video.genesis/TVShows/
20:16:57 74633.210938 T:1703670768   ERROR: Previous line repeats 1 times.
20:16:57 74633.210938 T:1703670768 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.mrknow/?mode=20
20:16:57 74633.210938 T:1703670768   ERROR: InputStream: Error opening, plugin://plugin.video.mrknow/?mode=20
20:17:01 74636.710938 T:1672471536  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1

**Comment by rysson** [comment]
@happy2w8, zobacz przez przeglądarkę. Po mojemu domenę wcięło:
```
zobaczto.tv’s DNS address could not be found.
```

**Comment by happy2w8** [comment]
no tak, ale podobny błąd mam na alltube.tv:

17:41:54 151729.937500 T:1680970736  NOTICE: [plugin.video.mrknow] Jest Alfabetycznie Litera: P
17:42:11 151747.250000 T:1265439728  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.12.1
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] ?category=None&icon=None&name=items-menu&service=alltubeseriale&strona&title=Pakt&url=http://alltube.tv/serial/pakt/2204
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] Handle: 90
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] Parameter: ?category=None&icon=None&name=items-menu&service=alltubeseriale&strona&title=Pakt&url=http%3a%2f%2falltube.tv%2fserial%2fpakt%2f2204
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] LEN: 120
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] mode: None
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] Starting alltubeseriale.pl
17:42:11 151747.390625 T:1265439728  NOTICE: [plugin.video.mrknow] Jest Sezon:
17:42:21 151757.468750 T:1265439728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.timeout'>
                                            Error Contents: timed out
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 928, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 373, in showListOptions
                                                tv.handleService()
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/alltubeseriale.py", line 291, in handleService
                                                self.listsItems(url,strona)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/alltubeseriale.py", line 128, in listsItems
                                                link = self.cm.getURLRequestData(query_data)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_pCommon.py", line 232, in getURLRequestData
                                                response = urlOpen(req, customOpeners)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_pCommon.py", line 179, in urlOpen
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 431, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 449, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
                                                response.begin()
                                              File "/usr/lib/python2.7/httplib.py", line 444, in begin
                                                version, status, reason = self._read_status()
                                              File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
                                                line = self.fp.readline(_MAXLINE + 1)
                                              File "/usr/lib/python2.7/socket.py", line 476, in readline
                                                data = self._sock.recv(self._rbufsize)
                                            timeout: timed out
                                            -->End of Python script error report<--
17:42:22 151757.718750 T:1957016496   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?category=None&icon=None&name=items-menu&service=alltubeseriale&strona&title=Pakt&url=http%3a%2f%2falltube.tv%2fserial%2fpakt%2f2204
17:42:22 151757.734375 T:1957016496   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?category=None&icon=None&name=items-menu&service=alltubeseriale&strona&title=Pakt&url=http%3a%2f%2falltube.tv%2fserial%2fpakt%2f2204) failed
17:43:04 151800.453125 T:1290605552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.mrknow/?mode=20
17:43:04 151800.453125 T:1290605552   ERROR: InputStream: Error opening, plugin://plugin.video.mrknow/?mode=20

**Comment by rysson** [comment]
```
timeout: timed out
```
Też coś z połączeniem. Może stream wskazuje na martwy host. Poczekajmy chwilę.
Swoją drogą warto by było ładne okienko pokazywać, zamiast walić wyjątkiem po logach. Pomyślimy...
