### ISSUE TITLE
Błąd dodatku Filmy online - Mrknow

### ISSUE THREAD

**Issue by KrzysiekZZZ** [mrknow/filmkodi#669]
## Kodi & OS
- Kodi verison: 16.1
- OS version: osmc 2016.11-1

---
## Addon / Wtyczka
- [ x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2016.11.26.3

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Wtyczka przestała odtwarzać filmy. Odinstalowałem, zainstalowałem i teraz przestała się uruchamiać. Logi są tutaj: http://paste.osmc.io/ogixetezuf
ekstrakt:

20:19:15 220.401505 T:1754256368 WARNING: CSkinInfo: failed to load skin settings
20:19:15 220.592728 T:1754256368   ERROR: EXCEPTION: Non-Existent Control 300
20:19:35 240.812897 T:1578390512 WARNING: CPythonInvoker(13): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
20:25:39 604.456787 T:1957209008   ERROR: GetDirectory - Error getting filmkodi.com/repository/
20:27:12 698.090454 T:1957209008   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
20:27:16 701.931030 T:1578390512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ("Non-ASCII character '\\xf3' in file /home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py', 1, 0, None))
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 111, in <module>
                                                import wykop, filmbox,vodpl, filmydokumentalne, efilmyseriale
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/wykop.py", line 14, in <module>
                                                import mrknow_pLog, mrknow_pCommon, mrknow_Parser,mrknow_urlparser
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_urlparser.py", line 18, in <module>
                                                import urlresolver9 as urlresolver
                                            SyntaxError: ("Non-ASCII character '\\xf3' in file /home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py', 1, 0, None))
                                            -->End of Python script error report<--

20:38:39  68.871109 T:1577841648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ("Non-ASCII character '\\xf3' in file /home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py', 1, 0, None))
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 111, in <module>
                                                import wykop, filmbox,vodpl, filmydokumentalne, efilmyseriale
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/wykop.py", line 14, in <module>
                                                import mrknow_pLog, mrknow_pCommon, mrknow_Parser,mrknow_urlparser
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_urlparser.py", line 18, in <module>
                                                import urlresolver9 as urlresolver
                                            SyntaxError: ("Non-ASCII character '\\xf3' in file /home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py', 1, 0, None))
                                            -->End of Python script error report<--
20:38:39  69.041183 T:1956328368   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/
20:38:42  71.747391 T:1956328368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/) failed
20:40:25 174.996750 T:1577841648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ("Non-ASCII character '\\xf3' in file /home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py', 1, 0, None))
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 111, in <module>
                                                import wykop, filmbox,vodpl, filmydokumentalne, efilmyseriale
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/wykop.py", line 14, in <module>
                                                import mrknow_pLog, mrknow_pCommon, mrknow_Parser,mrknow_urlparser
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_urlparser.py", line 18, in <module>
                                                import urlresolver9 as urlresolver
                                            SyntaxError: ("Non-ASCII character '\\xf3' in file /home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py', 1, 0, None))

Pozdrawiam.

**Comment by drrak** [comment]
To jest nas dwóch #663

**Comment by mrknow** [comment]
OK. To ciekawy przypadek. 

Zaktualizowałem wtyczkę script.mrknow.urlresolver do wersji "2016.12.10.1" 

Sprawdź, czy pomogło

**Comment by KrzysiekZZZ** [comment]
Dzień dobry,
niestety nie pomogło. Raczej nie będę miał czasu się tym zająć w tym tygodniu. Postaram się ogarnąć temat w przyszłym tygodniu i przesłać logi.
Jak napiszecie gdzie są pliki na kodi to mogę też zobaczyć jak wygląda to co jest zainstalowane.

**Comment by koladka** [comment]
Mr know padlo wszystko! Kiedy jakas poprawka tv
