### ISSUE TITLE
Openload & thevideo issues

### ISSUE THREAD

**Issue by ohmichael** [mrknow/filmkodi#774]
Nothing plays as of a couple days ago

**Comment by ddawid7** [comment]
me too,  nothing Alltube- Openload and CDA  . Error : ///

**Comment by dmacedonski** [comment]
Me too, Alltube not work, my log:

```
19:37:41.967 T:1697117168  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
19:37:41.968 T:1697117168  NOTICE: [plugin.video.mrknow] ?service=alltubeseriale&name=playSelectedMovie&category=None&title=Notatnik śmierci / Death Note / Desu n&ocirc;to [s01e13] Kokuhaku: Confession&url=http://alltube.tv/notatnik-smierci-death-note-desu-noto/kokuhaku-confession/odcinek-13-sezon-1/6950&icon=http://alltube.tv/static/normal/zztnle5aadl3.jpg&strona=
19:37:41.968 T:1697117168  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
19:37:41.969 T:1697117168  NOTICE: [plugin.video.mrknow] Handle: 3
19:37:41.969 T:1697117168  NOTICE: [plugin.video.mrknow] Parameter: ?service=alltubeseriale&name=playSelectedMovie&category=None&title=Notatnik śmierci / Death Note / Desu n&ocirc;to [s01e13] Kokuhaku: Confession&url=http%3A%2F%2Falltube.tv%2Fnotatnik-smierci-death-note-desu-noto%2Fkokuhaku-confession%2Fodcinek-13-sezon-1%2F6950&icon=http%3A%2F%2Falltube.tv%2Fstatic%2Fnormal%2Fzztnle5aadl3.jpg&strona=
19:37:41.969 T:1697117168  NOTICE: [plugin.video.mrknow] LEN: 311
19:37:41.969 T:1697117168  NOTICE: [plugin.video.mrknow] mode: None
19:37:42.262 T:1697117168  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2017.02.08.1
19:37:42.521 T:1697117168  NOTICE: [plugin.video.mrknow] Starting alltubeseriale.pl
19:37:42.524 T:1697117168  NOTICE: [MRKNOW]: Starting alltubefilmy
19:37:43.724 T:1697117168  NOTICE: [MRKNOW]: SSSSSSSSSSSSS {'PHPSESSID': 'a0hfb3kc3augabc72dsuccbvb0', 'history_watch': 'a%3A1%3A%7Bi%3A0%3Bs%3A183%3A%22%3Ca+href%3D%22http%3A%2F%2Falltube.tv%2Fnotatnik-smierci-death-note-desu-noto%2Fkokuhaku-confession%2Fodcinek-13-sezon-1%2F6950%22%3ENotatnik+%C5%9Bmierci+%2F+Death+Note+%2F+Desu+n%26ocirc%3Bto+-+Odcinek+13+Sezon+1%3C%2Fa%3E%22%3B%7D', '__cfduid': 'd310ba13e272534ed4b9ffb656f190c391488047863'}
19:37:43.734 T:1697117168  NOTICE: [MRKNOW]: Match1 [(u'http://alltube.tv/static/host/openload.png', u'openload', u' openload', u'aHR0cDovL2FsbHR1YmUudHYvc3BlY2lhbC5waHA/aG9zdGluZz1vcGVubG9hZCZpZD1KUXQ1WVhpY3BYRQ==', u'Lektor'), (u'http://alltube.tv/static/host/openload.png', u'openload', u' openload', u'aHR0cDovL2FsbHR1YmUudHYvc3BlY2lhbC5waHA/aG9zdGluZz1vcGVubG9hZCZpZD1yYVF2SXdRWWVqbw==', u'Lektor'), (u'http://alltube.tv/static/host/vshare.png', u'vshare', u' vshare', u'aHR0cDovL2FsbHR1YmUudHYvc3BlY2lhbC5waHA/aG9zdGluZz12c2hhcmUmaWQ9Zjg2MjQ4Yg==', u'Lektor'), (u'http://alltube.tv/static/host/openload.png', u'openload', u' openload', u'aHR0cDovL2FsbHR1YmUudHYvc3BlY2lhbC5waHA/aG9zdGluZz1vcGVubG9hZCZpZD1Sdkh6YUZCa1M2SQ==', u'Lektor'), (u'http://alltube.tv/static/host/cda.png', u'cda', u' cda', u'aHR0cDovL2FsbHR1YmUudHYvc3BlY2lhbC5waHA/aG9zdGluZz1jZGEmaWQ9MTY4Mzk1OGQ=', u'Lektor'), (u'http://alltube.tv/static/host/openload.png', u'openload', u' openload', u'aHR0cDovL2FsbHR1YmUudHYvc3BlY2lhbC5waHA/aG9zdGluZz1vcGVubG9hZCZpZD1fQkdPVlRRbElFWQ==', u'Lektor'), (u'http://alltube.tv/static/host/anyfiles.png', u'anyfiles', u' anyfiles', u'aHR0cDovL2FsbHR1YmUudHYvc3BlY2lhbC5waHA/aG9zdGluZz1hbnlmaWxlcyZpZD02OTI4', u'Lektor')]
19:37:43.738 T:1697117168  NOTICE: [MRKNOW]: Link ALL http://alltube.tv/special.php?hosting=openload&id=JQt5YXicpXE
19:37:43.739 T:1697117168  NOTICE: [MRKNOW]: Link ALL http://alltube.tv/special.php?hosting=openload&id=raQvIwQYejo
19:37:43.739 T:1697117168  NOTICE: [MRKNOW]: Link ALL http://alltube.tv/special.php?hosting=vshare&id=f86248b
19:37:43.739 T:1697117168  NOTICE: [MRKNOW]: Link ALL http://alltube.tv/special.php?hosting=openload&id=RvHzaFBkS6I
19:37:43.739 T:1697117168  NOTICE: [MRKNOW]: Link ALL http://alltube.tv/special.php?hosting=cda&id=1683958d
19:37:43.739 T:1697117168  NOTICE: [MRKNOW]: Link ALL http://alltube.tv/special.php?hosting=openload&id=_BGOVTQlIEY
19:37:43.739 T:1697117168  NOTICE: [MRKNOW]: Link ALL http://alltube.tv/special.php?hosting=anyfiles&id=6928
19:37:54.851 T:1697117168  NOTICE: [MRKNOW]: Altube wybrales [0]
19:37:54.870 T:1697117168  NOTICE: [MRKNOW]: RandomAgent {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36'}
19:37:54.950 T:1697117168  NOTICE: [MRKNOW]: XXXXXXXXXXX {'tmvh': '122c1758038cb91c3d348d4fbedb4643', 'PHPSESSID': 'a0hfb3kc3augabc72dsuccbvb0', 'history_watch': 'a%3A1%3A%7Bi%3A0%3Bs%3A183%3A%22%3Ca+href%3D%22http%3A%2F%2Falltube.tv%2Fnotatnik-smierci-death-note-desu-noto%2Fkokuhaku-confession%2Fodcinek-13-sezon-1%2F6950%22%3ENotatnik+%C5%9Bmierci+%2F+Death+Note+%2F+Desu+n%26ocirc%3Bto+-+Odcinek+13+Sezon+1%3C%2Fa%3E%22%3B%7D', '__cfduid': 'd310ba13e272534ed4b9ffb656f190c391488047863'}
19:37:55.035 T:1697117168  NOTICE: [MRKNOW]: Altube  link [<Response [200]>]
19:37:55.036 T:1697117168  NOTICE: [MRKNOW]: 2 All pageparser   YXYXYYX   PLAYYYYYYERRRRRRRRRRRR [http://openload.co/embed/JQt5YXicpXE]
19:37:55.401 T:1697117168  NOTICE: Mrknow URLResolver: Exception during openload resolve parse: local variable 'dec' referenced before assignment
19:37:55.402 T:1697117168   ERROR: Mrknow URLResolver: UnboundLocalError Error - From: openload Link: http://openload.co/embed/JQt5YXicpXE: local variable 'dec' referenced before assignment
19:37:55.440 T:1697117168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'dec' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 852, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 372, in showListOptions
                                                tv.handleService()
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/alltubeseriale.py", line 310, in handleService
                                                self.LOAD_AND_PLAY_VIDEO(url, title,'')
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/alltubeseriale.py", line 245, in LOAD_AND_PLAY_VIDEO
                                                VideoLink = self.alltube.getMovieLinkFromXML(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/alltubefilmy.py", line 216, in getMovieLinkFromXML
                                                return self.urlresolve(linkVideo)
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/__generic_host__.py", line 249, in urlresolve
                                                linkVideo = hmf.resolve()
                                              File "/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/hmf.py", line 196, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/plugins/openload.py", line 68, in get_media_url
                                                mylink = self.get_mylink(html)
                                              File "/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/plugins/openload.py", line 157, in get_mylink
                                                print("DEC",dec)
                                            UnboundLocalError: local variable 'dec' referenced before assignment
                                            -->End of Python script error report<--
19:37:55.709 T:1958515632   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mrknow/?service=alltubeseriale&name=playSelectedMovie&category=None&title=Notatnik śmierci / Death Note / Desu n&ocirc;to [s01e13] Kokuhaku: Confession&url=http%3A%2F%2Falltube.tv%2Fnotatnik-smierci-death-note-desu-noto%2Fkokuhaku-confession%2Fodcinek-13-sezon-1%2F6950&icon=http%3A%2F%2Falltube.tv%2Fstatic%2Fnormal%2Fzztnle5aadl3.jpg&strona=]
```

**Comment by ddawid7** [comment]
u mnie to samo z alltube żaden stream z openload nie działa .
a jak u ciebie z CDA ?

**Comment by dmacedonski** [comment]
@ddawid7 CDA u mnie również nie działa, ten sam błąd co wyżej.

**Comment by ddawid7** [comment]
http://wikisend.com/download/357434/plugin.video.mrknow.zip

**Comment by mrknow** [comment]
Fixed
