### ISSUE TITLE
Problem on Android devices

### ISSUE THREAD

**Issue by widgetpl** [mrknow/filmkodi#9]
Sony Xperia Z ( rooted )
Android 4.4.4

Amazon FireStick

Can't start MrKnow.pl plugin at all. Everything works ok Linux and Windows OS.

    <addon id="plugin.video.mrknow"
       name="Filmy Online - mrknow.pl"
       version="2015.11.29.2"
       provider-name="mrknow">

    20:09:13 T:2123132344  NOTICE: -->Python Interpreter Initialized<--
    20:09:14 T:2123132344  NOTICE: ('pluginDataDir', u'/storage/emulated/0/Android  /data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.module.xbmcfilm/')
    20:09:15 T:2123132344  NOTICE: [xbmcfilm.com  1] Filmy online www.mrknow.pl
    20:09:15 T:2123132344  NOTICE: Cache directory purged
    20:09:15 T:2123132344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'Parser' object has no attribute 'getParams'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mrknow/default.py", line 864, in <module>
                                                init.showListOptions(sys.argv)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mrknow/default.py", line 189, in showListOptions
                                                params = self.parser.getParams()
                                            AttributeError: 'Parser' object has no attribute 'getParams'
                                            -->End of Python script error report<--
    20:09:15 T:1902361856   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.mrknow/
    20:09:15 T:1902361856   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/) failed
    20:09:15 T:18446744071591603480  NOTICE: Thread BackgroundLoader start, auto delete: false
    20:09:20 T:18446744071578996432  NOTICE: Thread Timer start, auto delete: false

**Comment by widgetpl** [comment]
#5 and #6

**Comment by widgetpl** [comment]
fixed
